# Generated by Django 5.0.2 on 2024-03-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        
    ]
